# Generated by Django 3.2.5 on 2023-05-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('word_start', models.FloatField()),
                ('word_end', models.FloatField()),
                ('sentence_start', models.FloatField()),
                ('sentence_end', models.FloatField()),
                ('full_video', models.CharField(max_length=100)),
                ('sentece_video', models.CharField(default=None, max_length=100)),
                ('word_video', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
