# Generated by Django 3.2.5 on 2023-05-20 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230520_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='sentece_video',
            new_name='sentence_video',
        ),
    ]
