# Generated by Django 3.2.5 on 2023-05-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_sentece_video_word_sentence_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word_video',
            new_name='word_audio',
        ),
    ]
