# Generated by Django 3.2.5 on 2023-06-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_word_accent'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='film_name',
            field=models.CharField(default='Неизвестно', max_length=100),
        ),
    ]
